spring:
  application:
    name: base-zuul
server:
  port: 7000
eureka:
  client:
    register-with-eureka: true     #false表示不向注册中心注册自己。
    fetch-registry: true     #false表示自己端就是注册中心，我的职责就是维护服务实例，并不需要去检索服务
    service-url:
      defaultZone: http://192.168.199.190:8761/eureka/,http://192.168.199.190:8762/eureka/
zuul:
  routes:
    api-a:
      path: /api-a/**
      serviceId: base-feign
    api-b:
      path: /api-b/**
      serviceId: base-hystrix-dashboard